### ISSUE TITLE
OnPlayerJoin - add to permissions group(s)

### ISSUE THREAD

**Issue by admalledd** [Danielv123/factorioClusterio#100]
Should be possible via http://lua-api.factorio.com/latest/LuaPermissionGroup.html#LuaPermissionGroup.add_player right?

**Comment by Danielv123** [comment]
This sounds like something that would need a lot of UI stuff. I am thinking a web interface to set global permission groups for the whole cluster would be ideal, but I won't have time to work on it.

**Comment by Danielv123** [comment]
This issue was moved to Danielv123/playerManager#1
