### ISSUE TITLE
How do i start a server now?

### ISSUE THREAD

**Issue by XboySupCom** [Danielv123/factorioClusterio#108]
First of all: great mod at all and what i've saw is amazing till now!
the description/instruction is a bit incomplete in my opinion. It seams that the instruction starts somewhere in the middle and it ends nearly before the completion. - and there are no other informations about Clusterio...

My Problem now: after 1 hours to figuring out what: "copy config.json.dist to config.json" means, im finished with all points. 
and now? should i start a Server with the IP and Port settings? how do i start a server with those things and those million folders i've installed now? Should i use the command-lines in that Factorio.exe - i've copied - to start it as a "normal" server? are there some parameters i should add? and how do i start the Master or Client Server?

When i start those  master.js and client.js files, theres always a syntaxerror in the first lines of code.
Instances can be created only one single time before the ****.bat file gets stuck it self - everything else seams that it would work corectly but im not sure what now?

**Comment by Danielv123** [comment]
You should be starting the master.js and client.js files, but the syntax error might mean something went wrong in the install. I have had some problems with this on windows sytems. Try `node ./lib/npmPostinstall.js` and then `node master.js` and see if that helps.

**Comment by XboySupCom** [comment]
Ooh nice fast response :D yeah no problem if u going to bed. same for me soon
Reinstalled the previous 2 software now and did it what u said.
now the ***.bat for the master saying: 
Listening on port 8080...  
All plugins loaded in 25ms
sounds better then before.

but the ****.bat for the Client saying
ERROR invalid config
Master server now needs....             .... after running it once.

what now? i copied the config.json before moving on and stuff. and also the master.js file will run now but theres nothing in de "cmd" and when i start the client.js file it will run and close the windows automaticlly. dosent seam correctly?
