### ISSUE TITLE
How do we clear/reset the master database 

### ISSUE THREAD

**Issue by Davolution** [Danielv123/factorioClusterio#109]
Hi Daniel,

First of all, thank you for this great mod! Loving it, it's a really neat concept!
I was able to setup the master and 5 different instances, and played with a buddy for testing different scenarios and this work great.

My question is how can I reset or start with a clean database?
Can I still use the same instances previously created?

I'm not sure if what I did was the right thing but I tried by deleting the database folder. 
I restarted the master, then connect to an instance, remove the combinator inventory and put it back  on the ground: it's still shows the inventory from the cloud in game but when I go to the webmaster, it doesn't show the inventory. 

So here I am, looking for your help. 

Thanks alot!

**Comment by Danielv123** [comment]
Yes, you can. To reset the master, stop it then delete database/items.json

The reason the combinator might not have updated is because it might be slow, not sure about that.

**Comment by Davolution** [comment]
Whoo that was quick response for you!

Ok, I'll try that when back home, and see how long it would take to update the combinator.
I just wanted to confirm really that I didn't need to reinstall a fresh copy of Clusterio. 

Thanks for the support,

**Comment by Danielv123** [comment]
Heh, you got lucky, I was just checking my email 👍
