### ISSUE TITLE
Master server won't run

### ISSUE THREAD

**Issue by marek5816** [Danielv123/factorioClusterio#110]
Hello, I have problem when trying run master server on 64x bit windows that throwing this error, do you have any suggestions how to fix it ?

https://pastebin.com/UEgJExJ3

**Comment by Danielv123** [comment]
Yes, please try running `node lib/npmPostinstall.js`

**Comment by Danielv123** [comment]
Here is a link to our Discord, if you feel like talking there. https://discord.gg/5XuDkje

**Comment by marek5816** [comment]
Ok thanks, I go try it, if I have any other problem I go on discord :)

**Comment by Danielv123** [comment]
Ok, I will close this issue then.
