### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Lyrad8791** [Danielv123/factorioClusterio#112]
Greetings, tried to setup a clusterio server group and had a power outage. After getting everything back up and running I went to install the second instance of my servers and have failed to get back into the proper section of cmd to run the command to install extra servers. I have tried messaging you on discord but you aren't excepting messages and so on. Would love some help getting this up and running!

I have looked and looked around on google and such, and can find basically no information on how to set this up OTHER then this list you have. There needs to be a better guide or something incase such events that just happened in my case happen again. No one seems to setup anything like this very often because of this. I would have thought that after being around for a year plus and people showing their servers on youtube someone would have made a video on how to set this up. Guess I was wrong on that. Just my thoughts on that.

**Comment by Danielv123** [comment]
Sent you message on discord. I do acknowledge we need better instructions.

**Comment by Danielv123** [comment]
Turns out this was a bug with how clusterio handles mod uploads. Fixed by #010e527
