### ISSUE TITLE
Is it possible to run multiply instances of factorio in 1 server with master?

### ISSUE THREAD

**Issue by e-3-s** [Danielv123/factorioClusterio#113]
Hi there,

I have a server at home, ubuntu installed.
I wondered if there is a way to run multiply factorio "headless servers" with this mod and the master on 1 server.

Would be awesome

**Comment by Danielv123** [comment]
Yes, you can run as many servers as you want on your server. Simply open more terminals or use a process manager (screen, PM2 etc)

**Comment by e-3-s** [comment]
Aright good to know that it is possible.
I am trying to start the master server but I get this error

`[TAILING] Tailing last 15 lines for [master] process (change the value with --lines option)
/home/buurthuis/.pm2/logs/master-out-0.log last 15 lines:
0|master   | Generated new master authentication private key!

/home/buurthuis/.pm2/logs/master-error-0.log last 15 lines:
0|master   |     at Module.load (internal/modules/cjs/loader.js:566:32)
0|master   |     at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
0|master   |     at Function.Module._load (internal/modules/cjs/loader.js:498:3)
0|master   |     at Object.<anonymous> (/usr/lib/node_modules/pm2/lib/ProcessContainerFork.js:83:21)
0|master   | Error: listen EACCES 0.0.0.0:444
0|master   |     at Server.setupListenHandle [as _listen2] (net.js:1329:19)
0|master   |     at listenInCluster (net.js:1387:12)
0|master   |     at Server.listen (net.js:1475:7)
0|master   |     at Object.<anonymous> (/home/buurthuis/factoriocluster/factorioClusterio/master.js:947:10)
0|master   |     at Module._compile (internal/modules/cjs/loader.js:654:30)
0|master   |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
0|master   |     at Module.load (internal/modules/cjs/loader.js:566:32)
0|master   |     at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
0|master   |     at Function.Module._load (internal/modules/cjs/loader.js:498:3)
0|master   |     at Object.<anonymous> (/usr/lib/node_modules/pm2/lib/ProcessContainerFork.js:83:21)
`

**Comment by Danielv123** [comment]
That means there is already a server listening on port 444.  This might be because you launched 2 master processes on the same server, which you shouldn't ever need to do.

**Comment by Danielv123** [comment]
Oh, and somehow I didn't post the discord link https://discord.gg/5XuDkje
