### ISSUE TITLE
Unsupported platform for fsevents on Windows Server 2016 

### ISSUE THREAD

**Issue by Trapton** [Danielv123/factorioClusterio#121]
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

Clusterio running anyway, but maybe interesting for a future update.

**Comment by Danielv123** [comment]
This is not a problem, just a dependency not having to use one of its workarounds. Nothing to fix.
