### ISSUE TITLE
New material receiver or modify current one. 

### ISSUE THREAD

**Issue by lookout888** [Danielv123/factorioClusterio#124]
The current material receiver acts like a request chests. So if you want to pull stuff from the database and put it into the local logistics network,  you have to make sure the material receiver is out side the logistics network then belt it to provider chests or you create loops. I believe this should work more like a passive provider chests ( maybe a interface check box like "Request from buffer chests" ) . Or add another material receiver chests that also acts like a passive provider chest.

Also could be another Material transmitter that acts like a requester box. so you can request stuff from the logistics network directly to the database. ( this would require a ""built in"' Inventory combinator)
Mike

**Comment by AlienXAXS** [comment]
I believe this should be sorted now with a recent change to the actual mod. (here: https://github.com/Danielv123/factorioClusterioMod/pull/30)

In the next version of the Clusterio mod, you'll be able to request items directly from a Material Receiver building, as it's now seen as a buffer chest - just ensure that the requester chests have "Request from buffer chests" ticked in your builds.

Hopefully this helps you.
