### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Trapton** [Danielv123/factorioClusterio#126]
I tried to remove an old station with several Putchests with the destruction planner, but the error occurred.
I could repeat this problem several times.
The server ran after that, but first had to be restarted, so you can connect again. The savegame was in the case of the last save (connect a player)

If I had dismantled the station by hand, the error did not occur.

259.682 Error MainLoop.cpp:1029: Exception at tick 4565239: Error while running event clusterio::on_tick (ID 0)
__clusterio__/LinkedList.lua:115: attempt to index local 'toReturn' (a nil value)
 259.683 Error ServerMultiplayerManager.cpp:96: MultiplayerManager failed: "Error while running event clusterio::on_tick (ID 0)
__clusterio__/LinkedList.lua:115: attempt to index local 'toReturn' (a nil value)"
 259.683 Info ServerMultiplayerManager.cpp:698: mapTick(4565239) changing state from(InGame) to(Failed)

**Comment by Danielv123** [comment]
sounds like a proper bug. try asking in the development discord linked in the readme
