### ISSUE TITLE
pm2 status errored

### ISSUE THREAD

**Issue by sematula** [Danielv123/factorioClusterio#139]
I'm trying to start a new master node on Ubuntu Server 18.04, and getting the following in the logs:

0|master   | (node:4339) DeprecationWarning: prom-client - Passing a non-object to metrics constructor is deprecated
0|master   | Error: listen EACCES 0.0.0.0:443
0|master   |     at Server.setupListenHandle [as _listen2] (net.js:1329:19)
0|master   |     at listenInCluster (net.js:1387:12)
0|master   |     at Server.listen (net.js:1475:7)
0|master   |     at /home/sematula/factorioClusterio/master.js:924:11
0|master   |     at Object.<anonymous> (/home/sematula/factorioClusterio/master.js:1162:3)
0|master   |     at Module._compile (internal/modules/cjs/loader.js:654:30)
0|master   |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
0|master   |     at Module.load (internal/modules/cjs/loader.js:566:32)
0|master   |     at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
0|master   |     at Function.Module._load (internal/modules/cjs/loader.js:498:3)

**Comment by Danielv123** [comment]
You already have something listening on port 443. You can either stop that process or set sslPort to 0 in config.json.

**Comment by sematula** [comment]
Thanks, I'll try that.
