### ISSUE TITLE
Unification of API authentication methods

### ISSUE THREAD

**Issue by Danielv123** [Danielv123/factorioClusterio#177]
the new POST endpoint introduced by #176 requires auth  using the x-access-token header. All other POST endpoints will instead allow for a body of {token=""}. I believe the endpoint should either also accept this standard or be merged with the GET endpoint.

**Comment by Master-Guy** [comment]
```
app.post("/api/runCommand", (req,res) => {
	endpointHitCounter.labels(req.route.path).inc();
	var token = req.headers['x-access-token'];
```
That is the source that i used, so it's not all other POST endpoints.

**Comment by Danielv123** [comment]
That is certainly weird, there is no reason to ever call that endpoint without euth either. Every other post request uses authenticate.middleware from lib/authenticate.js

**Comment by psihius** [comment]
That endpoint needs fixing :)

On the /api/slaves - it is a GET request. Post is really for data manipulation. So your choices here are either make a different endpont (depending on what data you want - it may return way less info skilling, say, the whole meta key to cut down on traffic) or add a query parameter to the existing one to add additional data into the output and not hide RCON passwords, since the auth is basically the same token and nothing special - the only diff is request type, there is no additional security.

**Comment by Master-Guy** [comment]
I've compared it against the other POST endpoints:

/api/getID: no auth
/api/editSlaveMeta: authenticate.middleware and rcon password
/api/getSlaveMeta: password needed, but no verification against anything
/api/checkMod: no auth
/api/uploadMod: authenticate.middleware
/api/slaves: ['x-access-token']
/api/place: authenticate.middleware
/api/remove: authenticate.middleware
/api/runCommand: ['x-access-token']

It is most definitely not uniform either..

If wanted, I can modify the GET endpoint to check for a query parameter, but that is even less secure, and I expected that you would want the Master Token to be secure as possible.

We do also want to use the rest of the (meta) information, so for us it was more useful to have it in a single request. However, if you prefer a separate request that only returns the RCON passwords, that would be an option as well.

**Comment by Zeroto** [comment]
Why not check for a token in the get? You could return limited data if the token is not valid. Or probably even better would be

1. get without token -> return limited data
2. get with valid token -> return full data
3. get with invalid token -> return unauthorized

**Comment by psihius** [comment]
Well, there is a lot of opportunities to make the API uniform and apply proper strategies :)
Why `/api/editSlaveMeta` wants RCON password is a mystery to me. I don't think anyone calling it actually sends the rcon password ever, no wonder it does not work properly then...

**Comment by Danielv123** [comment]
/api/getSlaveMeta is certainly an odd one, especially considering its just a more filtered version of /api/slaves. Auth should just be removed from that one.

**Comment by Danielv123** [comment]
/api/getID should probably have auth - its only called once in client.js and is possible to abuse.
/api/editSlaveMeta is asking for password to avoid nodes spoofing each other - with the new /api/slaves, this is now a lost effort. It should be modified to accept token only.

**Comment by Master-Guy** [comment]
I'll start working tomorrow on unifying this. Should not take too long to do.

**Comment by Master-Guy** [comment]
https://github.com/Danielv123/factorioClusterio/pull/178
