### ISSUE TITLE
Question: Is there an API or a function that can pull the calculations/numbers of items cloud storage?

### ISSUE THREAD

**Issue by Sparky1492** [Danielv123/factorioClusterio#182]
My Thought is to be able to have a graph style view/page that looks similar to the in-game vanilla Production tab.

![20190726Clusterio](https://user-images.githubusercontent.com/945772/61977705-c7a58b80-afb4-11e9-9c9d-d61469616d92.png)
![20190726Factorio](https://user-images.githubusercontent.com/945772/61977711-cd9b6c80-afb4-11e9-81b9-afca027d2575.png)

**Comment by Danielv123** [comment]
The entire web interface is build around HTTP APIs, so basically all information you can see is available. The endpoint your are looking for for item counts is GET `/api/inventory`

If you want to draw production graphs, I highly recommend to use our Prometheus integration for gathering data and Grafana for visualization. The config is very simple, and it offers a great performing solution gathering a *lot* of statistics. All kills, production, consumption, playercounts, import, export etc, all sorted by instanceID.

All endpoints return JSON data, except /metrics which uses Prometheus standard format.

**Comment by Sparky1492** [comment]
Thank you very much!  I will look into this.  

Please keep up the Great work!
