### ISSUE TITLE
RCON Fails with messages over ~4KB

### ISSUE THREAD

**Issue by justarandomgeek** [Danielv123/factorioClusterio#34]
Sending a RCON command longer than about 4KB causes Factorio to log `RemoteCommandProcessor.cpp:297: Couldn't parse RCON data: Couldn't read from input file. File could be corrupted.` and drop RCON session. 

RCON spec says 4KB is max packet size, but Oxyd on IRC says Factorio should accept much larger messages: 

> @Oxyd   if (payloadSize > 100 \* 1024 \* 1024)
> @Oxyd     throw std::runtime_error("Maximum payload size exceeded");

I tried to find something doing packet-splitting in the simple-rcon library but was unable to do so. We should test more carefully sending large messages and/or fix the library and/or fragment our messages into smaller blocks if required.

**Comment by Danielv123** [comment]
So just how many signals am I able to send on 4 kb do you think? I'll split them up into more smaller commands and we'll see how that performs.

**Comment by justarandomgeek** [comment]
Some further discussion on IRC and testing of this by Plorrntus seems to show that this is indeed a limitation in Factorio somewhere. I wrote up [a quick mod](https://mods.factorio.com/mods/justarandomgeek/cmdbuffer) to allow buffered commands, so they can be assembled in RCON-sized chunks.
