### ISSUE TITLE
Production graph thats not shit

### ISSUE THREAD

**Issue by Danielv123** [Danielv123/factorioClusterio#35]
Thinking of switching chart.js for canvas.js as the latter is made for live updating charts, hopefully giving a lot more flexibility.

**Comment by Danielv123** [comment]
I have the chart looking fine, but a graph of what travels in and out of the interdimensional space seems kinda useless as that should always be very linear with as much going in as out. Would it be possible to let the mod send the production stats for each world to a file, and then that could be summed up?

@justarandomgeek

http://lua-api.factorio.com/latest/LuaForce.html#LuaForce.item_production_statistics

**Comment by justarandomgeek** [comment]
I just played around with the production statistics a bit, and it seems that we only get the data that's equivalent to the in-game production screen's All tab. I can report them, and you can do the deltas and charting and whatever on your side?

**Comment by Danielv123** [comment]
Sure, that should be fine. Does it give ALL the data since world creation at once, or only for a specified time interval, or statistics for the current tick (or something like that)?

**Comment by justarandomgeek** [comment]
Sorry, I never answered that - in case you haven't concluded from code/science by now, it reports the totals since world creation.
