### ISSUE TITLE
Linux support/Documentation

### ISSUE THREAD

**Issue by StripedMonkey** [Danielv123/factorioClusterio#37]
Looking at the mod I assume it is compatible with linux/should be fairly easy to make compatible and if it is I am happy to test it out for you and add in the documentation if you would like me to in order to install it (Not that its going to be any longer than the windows version)

**Comment by fienxjox** [comment]
I can confirm it is reasonably compatible with Linux although I had some performance issues when I tried it a few weeks ago.  I did not have time to test if that was just my map or something else (it was a large map).  Note on Mint/Ubuntu I had to manually install Node 6.4.0 as the one in the repository was not compatible.

**Comment by StripedMonkey** [comment]
Good to know, tomorrow I will attempt to run it and see how it goes. I'm on Arch but my server is ubuntu. I can confirm that Node is 4.2.6 in the repos as I'm using it to run a bot.

**Comment by Danielv123** [comment]
Confirmed to work on ubuntu with node 6.4.0+, if you are able to track down performance issues I am interested. If you have anything to add to the installation instructions, send a PR as I don't know linuxes well enough to write that on my own.

**Comment by StripedMonkey** [comment]
The first problem I encountered was
```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn ./factorio/bin/x64/factorio.exe ENOENT
```
which was a fairly easy fix of find/replace factorio.exe with factorio (there is no .exe at the end of the linux package)

The second Error I came into was
```
OUT:    0.000  Error Util.cpp:57: There is no package core in /home/monkey/Games/factorioserver/factorioClusterio/factorio/bin/x64\..\..\data
```
which is true,  if I try to list the contents of ~/home/monkey/Games/factorioserver/factorioCluserio/factorio/bin\..\..\data there is no such file or directory.
instead the actual path is ~/home/monkey/games/factorioserver/factorioCluserio/factorio/bin/../../data
I was actually stuck on this step for a while until I realized that it had already created the config.ini and the values had already been written >.< so that was a harder fix than it should have been.

Next problem:
```
OUT:    0.652 Error Util.cpp:57: Invalid visibility value, please check data/server-settings.example.json for correct format.
```
This one I'm surprised was an issue but anyways the reason for this is because the server-settings.json is supposed to be this:
```
  "visibility":
  {
    "public": true,
    "lan": true
  },
```
but instead is this:
``` 
   "visibility": "lan",
```
oh boy, now we're getting into the tedious junk.
```
OUT:    0.668 Error Main.cpp:509: Couldn't load the game for MP: Opening zip /home/monkey/Games/factorioserver/factorioClusterio/./instances/testing/save.zip 
```
I had factorio save the file as "test.zip" not "save.zip"

After all that work I finally got it to the point that it was working as in it said the server was running.

**Comment by StripedMonkey** [comment]
Once that was all sorted it seems like it works with no issues, I'll try messing with it later this afternoon.

**Comment by Danielv123** [comment]
The .exe issue should be fixed by checing process.platform for "win32" or "linux" and launching appropriately.

As for server settings, is that our packaged file thats outdated? I know they have made a few updates to server-settings.json.

Not sure about the config.ini file, maybe we should set it to rewrite every time? I don't know too much about those paths as that was justarandomgeeks contribution, but I am sure it could also be fixed with process.platform.

**Comment by StripedMonkey** [comment]
Probably, also something to note is that I *did not* have to update the
version of nodejs in order to run the server. For whatever reason "js" is
the command needed instead of "node" when running it. It appeared to run
fine without issues.
@fienxjox could you elaborate what issues you had in terms of performance
issues? I did not test it extensively especially in terms of large worlds.

**Comment by Danielv123** [comment]
Ubuntu documentation is now short and concise, far easier than the windows docs so I consider this done.
