### ISSUE TITLE
StdIO mode for linuxes

### ISSUE THREAD

**Issue by Danielv123** [Danielv123/factorioClusterio#42]
The factorio server does not attach properly to stdio on windows. It does fortunately do this on linuxes, so we could use an OS check and accept the proper interface if it works.

Should also look into windows 10 Bash on Ubuntu on Windows (WSL) as it seems to be able to run and pipe from the factorio server properly. This could possibly be the best way to run clusterio on windows, but rcon should still be left in as a backup.

Std might solve #34 size issues

#38 is also most likely an RCON related problem which would kindof be mitigated with this.

**Comment by Danielv123** [comment]
Current code draft:

`// clusterio example plugin
module.exports.main = function(messageInterface) {
 messageInterface('/c game.player.print "hello!"');
}
// client.js implementation
require(plugin[o]).main(client.exec, options{})`

**Comment by justarandomgeek** [comment]
I haven't tested it myself, but you may also be able to do `cmd /c "factorio.exe"` to get stdio pipes that are easier to handle. That's how I do it to get them into a terminal for (limited) manual interaction with SP at least!

**Comment by Danielv123** [comment]
cmd /c "factorio.exe --create map.zip" > loggfile.txt gives no output. factorio.exe --create map.zip > log.txt works fine in WSL/ubuntu

**Comment by Danielv123** [comment]
Skipping this as RCON is stable on linuxes and this isn't needed.
