### ISSUE TITLE
InventoryImports not ignoring 0 requests.

### ISSUE THREAD

**Issue by OdinYggd** [Danielv123/factorioClusterio#57]
On Leveller's clusterio node, at the time of my writing the count of iron plates is low. A recent change caused Clusterio to attempt to distribute the offending item evenly in this situation, but I believe the change has caused a nusiance issue. 

Each second, I get a console warning in-game of the following: 

Cannot execute command. Error: Item stack count has to be a positive number stack traceback [string "local a="1"local b={["iron-plate"]=0,}local c..."]:1: in main chunk

I'm about to connect additional iron supplies to the cluster, which I am pretty sure will fix the problem for the time being. Did a git pull and slave node restart a few minutes ago, so I should be current to this repository.

**Comment by Danielv123** [comment]
This is a problem with the inventory imports plugin and should be an easy fix. Will get it done later.
