### ISSUE TITLE
Remote mapping plugin

### ISSUE THREAD

**Issue by Danielv123** [Danielv123/factorioClusterio#61]
Using LUA portion of https://github.com/Windfisch/factorio-bot

* Writes out entities placed/removed in the world using a mod

* Parses them in a plugin, makes a database of all entities

* Tunnels through master using webRTC or something similar to provide on demand mapping on the web interface

**Comment by DDR0** [comment]
I can confirm e3e255b fixes the issue where combinators stop working if you have too much of something.

**Comment by Danielv123** [comment]
The remote mapping feature is now working, if in a basic state. I consider this issue resolved. Requests for additional features for remoteMap should go in their own issues.
