### ISSUE TITLE
Use template-literal instead of EJS

### ISSUE THREAD

**Issue by Drulac** [Danielv123/factorioClusterio#67]
[Template Literal](https://github.com/Drulac/template-literal) is fastest, smallest and simplest template engine, because it use JS's literal template feature.

It's  55 times faster than EJS, and it also use less CPU and RAM ressources, so it may be a good idea to use it instead of EJS 😀

**Comment by Danielv123** [comment]
It would make the application run about 0.00015% faster, if 100 ms was spent rendering EJS templates per day. I do not believe this is worth the effort.
