### ISSUE TITLE
Generate masterAuthSecret on first launch of the master

### ISSUE THREAD

**Issue by Danielv123** [Danielv123/factorioClusterio#86]
Currently we rely on people keyboardmashing their own secret key, which is bad (because people are unlikely to do that).

The solution would be to generate a new key upon first launching the master. As it is difficult to modify JSON files without screwing up order and comments, I think the masterAuthSecret should be stored in a .txt file.

**Comment by Elbrasch** [comment]
A quick test shows me that JSON.stringify(config) preserves the order of keys in the original file, so it can be as easy as inserting linebreaks in the right places.

**Comment by Danielv123** [comment]
Automatic formatting can be done as simply as JSON.stringify(config, null, 4), so it shouldn't be hard at all then.

**Comment by Danielv123** [comment]
Was fixed by above PR ages ago
