### ISSUE TITLE
Better UPS alerting/tracking

### ISSUE THREAD

**Issue by admalledd** [Danielv123/factorioClusterio#90]
Both on the cluster status pages AND in game.

* Cluster status page
  * UPS over time
  * CPU % over time (NOTE: CPU usage should be scoped to one-ish core, thus reflecting % cap of max UPS)
  * Basically, MOAR graphs and statistics please on the cluster master.
~~* In-game alerts/warnings~~
  ~~* As CPU crosses critical thresholds, note it to in-game users.~~
    ~~* CPU > 50%~~
    ~~* CPU > 75%~~
    ~~* CPU > 90%~~
  ~~* UPS alerts if/when it dips below 60 for <x> timespan (30 seconds? 60? five minutes?)~~

**Comment by Danielv123** [comment]
UPS over time I can do. CPU over time might be hard.

In game alerts would be really hard, as there is no good way to alert that without being really spammy as it may fluctuate.

**Comment by admalledd** [comment]
Do you have the PID of the factorio instance? And do I understand correctly that linux is the currently main targeted platform? If so, here is a python script from my archive showing how to read /proc/<pid>/stat for CPU usage as %. It isn't perfect (accuracy is porportionate to polling period, etc), but a 2-5s interval of the same logic should be plenty I would think.

    #!/usr/bin/python2
    
    import time
    import sys
    import os
    
    pid = sys.argv[1]
    poll = float(sys.argv[2])
    
    tick_per_s = os.sysconf(os.sysconf_names['SC_CLK_TCK'])
    
    def getUS():
            with open("/proc/"+pid+"/stat","r") as f:
                    elms = f.read().split(' ')
                    utime = int(elms[13]) #%lu user space timing since exec()
                    stime = int(elms[14]) #%lu  sys space timing since exec()
                    return utime+stime
    
    start = getUS()
    time.sleep(poll)
    end = getUS()

    delta = end-start
    print start,end,delta
    print 100*(delta/float(tick_per_s*poll))

(convert to JS... us some sort of background polling/SetInterval()?)

Else, I would think there are some proc/stat libraries on npm if you have the PID...

I think CPU Usage % is more important than UPS. This is because players need to know/be aware of how close to max load they are. Knowing that UPS is dipping is too late IMO.

**Comment by Danielv123** [comment]
Yes, I do. I can get that by child_process.pid

https://github.com/soyuka/pidusage can be used for getting CPU usage etc.

**Comment by Danielv123** [comment]
Added UPS and gametick reporting to the /metrics endpoint for prometheus. Did not add CPU metrics, but feel free to implement it if you want.
