### ISSUE TITLE
off-node backup/archiving

### ISSUE THREAD

**Issue by admalledd** [Danielv123/factorioClusterio#91]
As shown, there is some potential for corrupting maps, lost configs, or even having nodes fall out of cluster forever.

* A off-node backup of the map save every $INTERVAL to some remote host, allowing admin recovery of maps in event of failure/corruptions.
* A off-master backup of master's DB itself (such we don't suffer a repeat of loosing the master inv again and rely on being lucky). Still requires someone to not delete or manually have a backup of the master secret key though!

NOTE: I have about 1TB free on my main WWW server for storage. Just needs a front-end.

**Comment by Danielv123** [comment]
This sounds like it should be handled by an external solution. Just occasionally upload the instances/ and database/ folder.
