### ISSUE TITLE
Use ramdisk for communication with factorio

### ISSUE THREAD

**Issue by Elbrasch** [Danielv123/factorioClusterio#96]
Mounting a Ramdisk in /instance/X/script-output before starting factorio allows for (somewhat, linux is quite good at caching) quicker responsetimes and removes any wear from SSDs.
While I know how to do this under linux (create folder in /dev/shm and symlink it), I am uncertain if this is possible under windows/how to do it.

**Comment by Danielv123** [comment]
This issue should be resolved by moving IO to rcon instead, as that can now return data as well.
